# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem 'sinatra',"1.4.0"
gem 'sinatra-contrib'
gem 'activerecord',"4.2.7"
gem 'sqlite3',"1.3.13" 
gem 'bigdecimal', '1.3.5' #NoMethodError: undefined method `new' for BigDecimal:Classの対処法
# gem "rails"
